@startuml

participant "coefDividendo[]" as coefDividendo
participant "resultado[]" as resultado
participant "i" as i

loop
    i -> i: i = i + 1
    coefDividendo -> coefDividendo: Pegar coefDividendo[i]
    coefDividendo --> resultado: Passar coeficiente
    resultado --> resultado: Atualizar resultado[i+1]
end loop

@enduml
